name: drupal-security-automation
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: ""
web_environment: []
nodejs_version: "16"
hooks:
  post-start:
    - composer: install
  post-composer:
    - exec-host: ddev rebuild
    - exec: drush uli
    - exec-host: ddev launch /user
  post-import-db:
    - exec-host: ddev rebuild
    - exec: drush dcdi
    - exec: "drush uli"
    - exec-host: ddev launch /user
  # take a db snapshot when stopping the site to ensure no accidental data loss
  # to restore a snapshot use 'ddev snapshot restore' and follow the prompts
  pre-stop:
    - exec-host: "ddev snapshot"

